[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Belectric's BESS Boards"
authors = [{name = "Louis Green", email = "louis.green@belectric.com"}]
dynamic = ["version", "description"]
